REM *********************************************************************
REM >>>>>>>>>Dont use or change this script without permission<<<<<<<<<<<
REM *********************************************************************
REM
REM     Author: Irvino
REM     e-mail: irvino@irvino.com
REM     Copyright (c) Irvino 2011
REM
REM *********************************************************************

SELECT
	RNC.OBJECT_INSTANCE RncId,
	WBTS.NAME WBTS_NAME,
	CWCEL.WCEL_CELL_ID CELL_ID,
	WBTS.OBJECT_INSTANCE WBTSId,
	CWCEL.WCEL_ID LcrId,
	COMTOPOVW.CTOP_OBJ_DN WCELDN,
	WCEL.NAME WCel_NAME,
	decode(COMTOPOVW.CTOP_ADMIN_STATE,'0','ADM_UNKNOWN',/*
	*/'1','ADM_UNLOCKED',/*
	*/'2','ADM_SHUTDOWN',/*
	*/'3','ADM_LOCKED') ADMIN_STATE,
	CWCEL.WCEL_RAC RAC,
	CWCEL.WCEL_PRI_SCR_CODE PriScrCode,
	CWCEL.WCEL_PTX_PRIMARY_CPICH PtxPrimaryCPICH,
	CWCEL.WCEL_S_SEARCH_RAT Ssearch_RAT,
	CWCEL.WCEL_QQUAL_MIN QqualMin,
	CWCEL.WCEL_QHYST1 Qhyst1,
	CWCEL.WCEL_lac LAC,
	wbts.ip_address ip,
    WCEL.INT_ID INT_ID
  FROM
	OBJECTS RNC,
	OBJECTS WBTS,
	OBJECTS WCEL,
	C_RNC CRNC,
	C_WBTS CWBTS,
	C_WCEL CWCEL,
	C_OBJ_RESOLVE_VW RRNC,	
	C_OBJ_RESOLVE_VW RWBTS,
	C_COMMON_TOPOLOGY_VW COMTOPOVW
WHERE
	RNC.OBJECT_CLASS=811
	AND 
	WBTS.OBJECT_CLASS=812
	AND 
	WCEL.OBJECT_CLASS=813
	AND
	RNC.INT_ID=WBTS.PARENT_INT_ID
	AND
	WBTS.INT_ID=WCEL.PARENT_INT_ID
	AND
	RNC.INT_ID=RRNC.INT_ID
	AND
	RRNC.OBJ_GID=CRNC.OBJ_GID
	AND
	WBTS.INT_ID=RWBTS.INT_ID
	AND
	RWBTS.OBJ_GID=CWBTS.OBJ_GID
	AND
	CRNC.CONF_ID=CWBTS.CONF_ID
	AND
	CWBTS.CONF_ID=CWCEL.CONF_ID
	AND
	CWCEL.WCEL_RNC_ID=RNC.OBJECT_INSTANCE
	AND
	CWCEL.WCEL_WBTS_ID=WBTS.OBJECT_INSTANCE
	AND
	CWCEL.WCEL_ID=WCEL.OBJECT_INSTANCE
	AND
	COMTOPOVW.CTOP_OBJ_INT_ID=WCEL.INT_ID
	AND
	COMTOPOVW.CTOP_OBJ_GID=CWCEL.OBJ_GID
	AND
	COMTOPOVW.CTOP_TYPE_ID=1
	AND
	COMTOPOVW.CTOP_CONF_ID=1
	AND
	COMTOPOVW.CTOP_OBJ_CLASS=813
	AND
	COMTOPOVW.CTOP_STATE=0
ORDER BY
	RNC.OBJECT_INSTANCE, WBTS.NAME
;